# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MianWnd.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EasyEngBook(object):
    def setupUi(self, EasyEngBook):
        EasyEngBook.setObjectName("EasyEngBook")
        EasyEngBook.resize(423, 382)
        self.centralwidget = QtWidgets.QWidget(EasyEngBook)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(310, 20, 91, 151))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_SelectFile = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_SelectFile.setObjectName("btn_SelectFile")
        self.verticalLayout.addWidget(self.btn_SelectFile)
        self.btn_SelectOutPath = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_SelectOutPath.setObjectName("btn_SelectOutPath")
        self.verticalLayout.addWidget(self.btn_SelectOutPath)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 20, 261, 150))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.textEdit_File = QtWidgets.QTextEdit(self.verticalLayoutWidget_2)
        self.textEdit_File.setObjectName("textEdit_File")
        self.verticalLayout_2.addWidget(self.textEdit_File)
        self.textEdit_OutPath = QtWidgets.QTextEdit(self.verticalLayoutWidget_2)
        self.textEdit_OutPath.setObjectName("textEdit_OutPath")
        self.verticalLayout_2.addWidget(self.textEdit_OutPath)
        self.textEdit_Info = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_Info.setGeometry(QtCore.QRect(20, 200, 381, 121))
        self.textEdit_Info.setObjectName("textEdit_Info")
        EasyEngBook.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(EasyEngBook)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 423, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        EasyEngBook.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(EasyEngBook)
        self.statusbar.setObjectName("statusbar")
        EasyEngBook.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(EasyEngBook)
        self.action.setObjectName("action")
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(EasyEngBook)
        QtCore.QMetaObject.connectSlotsByName(EasyEngBook)

    def retranslateUi(self, EasyEngBook):
        _translate = QtCore.QCoreApplication.translate
        EasyEngBook.setWindowTitle(_translate("EasyEngBook", "MainWindow"))
        self.btn_SelectFile.setText(_translate("EasyEngBook", "PushButton"))
        self.btn_SelectOutPath.setText(_translate("EasyEngBook", "PushButton"))
        self.menu.setTitle(_translate("EasyEngBook", "设置"))
        self.menu_2.setTitle(_translate("EasyEngBook", "网络"))
        self.action.setText(_translate("EasyEngBook", "选择文件"))
        self.action.setToolTip(_translate("EasyEngBook", "选择Txt文本"))
